site_name: Centro de Analítica e Inteligencia Clínica - Hosvital HIS
site_url: https://soportesaludtech.github.io/superset-docs/
site_description: Repositorio técnico, funcional y normativo de indicadores de gestión clínica y financiera.
site_author: Dirección de Analítica y Soluciones en Salud

theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Modo Oscuro
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Modo Claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - tables
  - attr_list

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Inicio: index.md
  - Gestión Asistencial:
      - Consola Egresos y Urgencias: dashboards/01-egresos-urgencias.md
      - Consola Análisis de Ingresos: dashboards/consola_analisis_ingresos.md
      - Consola Calidad, Seguridad e IAAS: dashboards/04-vigilancia-iaas.md
      - Consola Vigilancia en Salud Pública (SIVIGILA): dashboards/05 - Sivigila.md
      - Consola Riesgo y Altocosto: dashboards/06-alto-costo-cac.md
      - Consola y Cohortes CAC: dashboards/07-consola-y-cohortes-cac.md
      - Consola de Gestión y Cohortes - Enfermedades Crónicas: dashboards/08-consola_gestion_cohortes_cronicas.md
      - Consola Estadísticas de Trauma: dashboards/09-consola_estadisticas_trauma.md
  - Gestión Financiera:
      - Prefacturación y Producción: dashboards/02-prefacturacion.md
  - Gestión Quirúrgica:
      - Ocupación y Programación QX: dashboards/03-ordenes-quirurgicas.md
